name: Flutter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v3

      - name: Flutter o'rnatish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter testlarni ishga tushirish
        run: flutter test
